{
 "title": "Yandex Cloud Audit Trails",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "trail",
    "query": {
     "query": "label_values(trail_processed_events_count, trail)"
    }
   },
   {
    "name": "event_source",
    "query": {
     "query": "label_values(trail_processed_events_count{trail=\"$trail\"}, event_source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Trails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Trails by status - $trail",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trail_status{status=\"ACTIVE\", trail=~\"$trail\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trails events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Processed events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(event_source) (trail_processed_events_count{trail=\"$trail\",event_source=~\"$event_source\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivered events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(event_source) (trail_delivered_events_count{trail=\"$trail\",event_source=~\"$event_source\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unauthorized events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(event_source) (trail_unauthorized_events_count{trail=\"$trail\",event_source=~\"$event_source\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trail quota usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "quota_trails_count_usage", "legendFormat": "{{__name__}}" },
    { "expr": "quota_trails_count_limit", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}