global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "compute"
    scrape_interval: 1m
    metrics_path: "/metrics/compute"
    static_configs:
    - targets: ["exporter:9000"]
  - job_name: "audit-trails"
    scrape_interval: 1m
    metrics_path: "/metrics/audit-trails"
    static_configs:
    - targets: ["exporter:9000"]
  - job_name: "all"
    scrape_interval: 1m
    metrics_path: "/metrics/all"
    static_configs:
    - targets: ["exporter:9000"]
